server:
  port: 8081
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        password: nacos
        #单机
        #server-addr: 127.0.0.1:8848
        #集群
        server-addr: 127.0.0.1:8847,127.0.0.1:8849,127.0.0.1:8851
        username: nacos
        #是否临时实例
        ephemeral: true
        #若注册为非临时实例 无法正常删除
        #删除需bash执行 nacos2.X文档 用户指南 Open API 指南
        #        curl -d 'serviceName=service-consumer' \
        #        -d 'ip=192.168.10.191' \
        #        -d 'port=8081' \
        #        -d 'weight=0.9' \
        #        -d 'ephemeral=false' \
        #        -d 'username=nacos' \
        #        -d 'password=nacos' \
        #        -X DELETE 'http://127.0.0.1:8848/nacos/v2/ns/instance'
